name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Lint check
        run: npm run lint

      - name: Run validation tests
        run: npm run test:phase1:validation

      - name: Build validation
        env:
          # Mock environment variables for public repo builds (100+ char requirement)
          NEXT_PUBLIC_SUPABASE_URL: https://mock.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: mock-anon-key-for-build-that-is-over-one-hundred-characters-long-to-satisfy-validation-requirements-in-github-actions
          SUPABASE_SERVICE_ROLE_KEY: mock-service-key-for-build-that-is-over-one-hundred-characters-long-to-satisfy-validation-requirements-in-github-actions
          SUPABASE_URL: https://mock.supabase.co
          SUPABASE_ANON_KEY: mock-anon-key-for-build-that-is-over-one-hundred-characters-long-to-satisfy-validation-requirements-in-github-actions
          NODE_ENV: production
        run: npm run build